config/routes.rb
Rails.application.routes.draw do
  resources :extintors
  devise_for :admins
  get 'admin' => 'admin#home'
  devise_for :users
  resources :leads
  resources :cities
  #devise_for :installs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
get 'creatives/index'
root 'creatives#index'
get 'system/index'
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
end

app/models/client.rb
class Client < ApplicationRecord
	
	validates :razon_social, :presence => true
	validates :tipo_cliente, :presence => true
	validates :contacto_principal, :presence => true
	validates :direccion_principal, :presence => true
	validates :nit, :presence => true

	validates :telefono_empresa, presence: true, unless: ->(client){client.celular_empresa.present?}
	validates :celular_empresa, presence: true, unless: ->(client){client.telefono_empresa.present?}
	
	validates :telefono_contacto_principal, presence: true, unless: ->(client){client.celular_contacto_principal.present?}
	validates :celular_contacto_principal, presence: true, unless: ->(client){client.telefono_contacto_principal.present?}

	validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i

	validates :ciudad, :presence => true
	validates :pais, :presence => true

end

app/models/extintor.rb
class Extintor < ApplicationRecord
end

app/models/install.rb
class Install < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/lead.rb
class Lead < ApplicationRecord

	validates :nombres, :presence => true
	validates :apellidos, :presence => true
	validates :email, :presence => true

	validates_numericality_of :telefono, allow_nil: true
  validates_numericality_of :celular, allow_nil: true

	validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i

	validate :telefono_or_celular
	validate :agendo_and_tiposervicio
	validate :agendo_and_hora_servicio
	validate :agendo_and_fecha_servicio

	private

	def telefono_or_celular
      if celular.blank? && telefono.blank?
        errors.add(:base, "Especifica por lo menos, el teléfono o celular")
      end
    end

    def agendo_and_tiposervicio
      if agendo_serv == 'Si' && tipo_servicio == "--"
        errors.add(:base, "Especifica el tipo de servicio")
      end
    end

    def agendo_and_hora_servicio
      if agendo_serv == 'Si' && hora_de_servicio == "--"
        errors.add(:base, "Especifica la hora de servicio")
      end
    end

    def agendo_and_fecha_servicio
      if agendo_serv == 'Si' && fecha_de_servicio.blank?
        errors.add(:base, "Especifica la fecha de servicio")
      end
    end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  #before_action :authenticate_admin!
  def home

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
	def new
	end

	def create
		#render plain: params[:lead].inspect 
		@city = City.new cities_params
		@city.save

		redirect_to '/'
	end

end

private

	def cities_params
		params.require(:city).permit(:ciudad, :pais)
	end
	

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
end

app/controllers/creatives_controller.rb
class CreativesController < ApplicationController
  layout "creative"

  def index
  end
end

app/controllers/extintors_controller.rb
class ExtintorsController < ApplicationController
  before_action :set_extintor, only: [:show, :edit, :update, :destroy]

  # GET /extintors
  # GET /extintors.json
  def index
    @extintors = Extintor.all
  end

  # GET /extintors/1
  # GET /extintors/1.json
  def show
  end

  # GET /extintors/new
  def new
    @extintor = Extintor.new
  end

  # GET /extintors/1/edit
  def edit
  end

  # POST /extintors
  # POST /extintors.json
  def create
    @extintor = Extintor.new(extintor_params)

    respond_to do |format|
      if @extintor.save
        format.html { redirect_to @extintor, notice: 'Extintor was successfully created.' }
        format.json { render :show, status: :created, location: @extintor }
      else
        format.html { render :new }
        format.json { render json: @extintor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /extintors/1
  # PATCH/PUT /extintors/1.json
  def update
    respond_to do |format|
      if @extintor.update(extintor_params)
        format.html { redirect_to @extintor, notice: 'Extintor was successfully updated.' }
        format.json { render :show, status: :ok, location: @extintor }
      else
        format.html { render :edit }
        format.json { render json: @extintor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /extintors/1
  # DELETE /extintors/1.json
  def destroy
    @extintor.destroy
    respond_to do |format|
      format.html { redirect_to extintors_url, notice: 'Extintor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_extintor
      @extintor = Extintor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def extintor_params
      params.fetch(:extintor, {})
    end
end

app/controllers/leads_controller.rb
 class LeadsController < ApplicationController

 	before_action :set_image, only:[:show, :edit, :update, :destroy]

	def index
		@leads = Lead.all
	end

	def new
		@lead = Lead.new
	end

	def create
		#render plain: params[:lead].inspect 
		@lead = Lead.new leads_params
		
		if @lead.save
			return redirect_to '/'
		end

		render :new

	end

	def show
	end

	def edit
	end

	def update
		@lead.update leads_params
		redirect_to leads_path
	end

	def destroy
		@lead.destroy
		redirect_to leads_path
	end

end

private

	def leads_params
		params.require(:lead).permit(:nombres, :apellidos, :email ,:telefono, :celular, :direccion, :ciudad, :fecha_de_servicio, :hora_de_servicio, :observaciones, :estado, :agendo_serv, :tipo_servicio)
	end

	def set_image
		@lead = Lead.find params[:id]
	end

app/controllers/system_controller.rb
class SystemController < ApplicationController
	def index
	end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/extintors_helper.rb
module ExtintorsHelper
end

app/helpers/leads_helper.rb
module LeadsHelper
end

app/helpers/system_helper.rb
module SystemHelper
end

app/views/cities/index.html.erb
<p>Hola desde el index de ciudades </p>
<%= render 'cities/new' %>

app/views/cities/new.html.erb
<%= form_for :city, url: cities_path do |f| %>
<div class="row">
	<div class="col-6 col-md-6">
		<div class="form-group">
			<%= f.label :ciudad, "Ciudad" %>
			<%= f.text_field :ciudad, class: 'form-control'%>
		</div>
		<div class="form-group">
			<%= f.label :pais, "Pais" %>
			<%= f.text_field :pais, class: 'form-control'%>
		</div>
	</div>
</div>
<div class="actions">
    <%= f.submit "Enviar" , class:'btn btn-lg btn-primary btn-block'%>
</div>
<% end %>

app/views/extintors/_form.html.erb
<%= form_with(model: extintor, local: true) do |form| %>
  <% if extintor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(extintor.errors.count, "error") %> prohibited this extintor from being saved:</h2>

      <ul>
      <% extintor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/extintors/edit.html.erb
<h1>Editing Extintor</h1>

<%= render 'form', extintor: @extintor %>

<%= link_to 'Show', @extintor %> |
<%= link_to 'Back', extintors_path %>

app/views/extintors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Extintors</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @extintors.each do |extintor| %>
      <tr>
        <td><%= link_to 'Show', extintor %></td>
        <td><%= link_to 'Edit', edit_extintor_path(extintor) %></td>
        <td><%= link_to 'Destroy', extintor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Extintor', new_extintor_path %>

app/views/extintors/new.html.erb
<h1>New Extintor</h1>

<%= render 'form', extintor: @extintor %>

<%= link_to 'Back', extintors_path %>

app/views/extintors/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_extintor_path(@extintor) %> |
<%= link_to 'Back', extintors_path %>

app/views/leads/_form.html.erb
<% if @lead.errors.any? %>
	<div class="alert alert-danger">
		<h4 class="alert-heading">Ha ocurrido uno o varios errores</h4>
		<ul>
  		<% @lead.errors.full_messages.each do |msg| %>
    		<li><%= msg %></li>
		<% end %>
		</ul>
	</div>
<% end %>

<%= form_for @lead do |f| %>
<div class="row">
	<legend>Datos personales</legend>
	<div class="form-group col-md-6">
		<%= f.label :nombres, 'Nombres'%>
		<div class="input-group">
           	<span class="input-group-addon">
           		<i class="glyphicon glyphicon-user"></i>
           	</span>			
		<%= f.text_field :nombres, class: 'form-control', placeholder:'Nombres', id:'nombresLead' %>
		</div>
	</div>
	<div class="form-group col-md-6">
		<%= f.label :apellidos, 'Apellidos'%>
		<div class="input-group">
           	<span class="input-group-addon">
           		<i class="glyphicon glyphicon-user"></i>
           	</span>
		<%= f.text_field :apellidos, class: 'form-control', placeholder:'Apellidos', id:'apellidosLead' %>
		</div>
	</div>
</div>
<div class="row">
	<div class="form-group col-md-4">
		<%= f.label :email, 'Correo electrónico'%>
		<div class="input-group">
			<span class="input-group-addon">
				<i class="glyphicon glyphicon-envelope"></i>
			</span>
			<%= f.text_field :email, class: 'form-control', placeholder:'Correo electrónico', id:'emailLead' %>
		</div>
	</div>
	<div class="form-group col-md-4">
		<%= f.label :telefono, 'Teléfono'%>
		<div class="input-group">
			<span class="input-group-addon">
				<i class="glyphicon glyphicon-phone-alt"></i>
			</span>
		<%= f.text_field :telefono, class: 'form-control', placeholder:'Teléfono' , id:'telefonoLead' %>
		</div>
	</div>
	<div class="form-group col-md-4">
		<%= f.label :celular, 'Celular'%>
		<div class="input-group">
			<span class="input-group-addon">
				<i class="glyphicon glyphicon-earphone"></i>
			</span>
		<%= f.text_field :celular , class: 'form-control', placeholder:'Celular', id:'celularLead' %>
		</div>
	</div>
</div>
<div class="row">
	<div class="col-md-6" style="padding-bottom: 5px;">
		<label for=Pregunta class="form-check-label">
			Le gustaría agendar un servicio?
		</label>
	</div>
	<div class="custom-control custom-radio custom-control-inline" data-toggle="buttons-radio">
		<div class="col-md-3 text-center">
			<%= f.label :agendo_serv, "Si", :value => "true" , class:'custom-control-label'  %>
		    <%= f.radio_button :agendo_serv, "Si" , class:'custom-control-input form-check-input with-gap' , id:'Agendo' %>
		</div>
		<div class="col-md-3">
		    <%= f.label :agendo_serv, "No", :value => "false" , class:'custom-control-label' %>
		    <%= f.radio_button :agendo_serv, "No", :checked => true , class:'custom-control-input form-check-input with-gap', id:'NoAgendo' %>
  		</div>
	</div>
</div>
<div class="row hidden" id="section_tiposervicio">
	<legend>Datos del servicio</legend>
	<div class="form-group col-md-12">
		<%= f.label :tipo_servicio, "Tipo de Servicio" %>
		 <div class="input-group">
             <span class="input-group-addon" style="max-width: 100%;">
             	<i class="glyphicon glyphicon-list"></i>
             </span>
		<%= f.select :tipo_servicio, ["--","Control Integral de Plagas" , "Recarga de Extintores"],{}, {class: "form-control" , id:'TipoServicioLead'}%>
		</div>
	</div>
</div>
<div class="row hidden" id="section_date">
	<div class="form-group col-md-3">
		<%= f.label :ciudad, "Ciudad" %>
		<div class="input-group">
             <span class="input-group-addon" style="max-width: 100%;">
             	<i class="glyphicon glyphicon-th"></i>
             </span>
		<%= f.select :ciudad, ["--","Cali", "Bogota","Medellin"],{}, {class: "form-control", id:"CiudadLead"}%>
		</div>
	</div>
	<div class="form-group col-md-6">
		<%= f.label :fecha_de_servicio, "Fecha en que necesitas el servicio" %>
            <div class='input-group date' id='datetimepicker1'>
            	<span class="input-group-addon">    
                        <span class="glyphicon glyphicon-calendar"></span>
                </span>
                 <%= f.text_field :fecha_de_servicio, "data-provide" => 'datetimepicker', class: 'form-control' , id:'FechaServicioLead' %>
            </div>
    </div>
    <div class="form-group col-md-3">
		<%= f.label :hora_de_servicio, "Horario" %>
		<div class="input-group">
	    	<span class="input-group-addon">    
		                <span class="glyphicon glyphicon-time"></span>
		    </span>	
		<%= f.select :hora_de_servicio, ['--','Mañana','Medio día','Tarde','Noche'], {}, {class: "form-control", id:'HoraServicioLead'} %>
		</div>
	</div>
</div>
<div class="row hidden" id="section_dir">
	<div class="form-group col-md-12">
		<%= f.label :direccion, "Dirección" %>
		<div class="input-group">
	    	<span class="input-group-addon">    
		         <span class="glyphicon glyphicon-road"></span>
		    </span>
			<%= f.text_field :direccion, class: 'form-control', placeholder:'Dirección', id:'DireccionLead' %>
		</div>
	</div>
</div>
<div class="row">
	<div class="form-group col-md-12">
		<%= f.label :observaciones, "Observaciones (opcional)" %>
		<div class="input-group">
			<span class="input-group-addon">
				<i class="glyphicon glyphicon-text-size"></i>
			</span>
		<%= f.text_area :observaciones, class:'form-control' , id:'ObservacionesLead' %>
		</div>
	</div>
	<div class="hidden">
		<%= f.text_area :estado, :value => "Por contactar"  %>
	</div>
</div>

<script type="text/javascript">
	

    $(function () {
        $('#datetimepicker1').datetimepicker({
        	format: 'DD/MM/YYYY'
        });
    });
    $("#Agendo").click(function(){
    	$("#section_dir").removeClass("hidden");
    	$("#section_date").removeClass("hidden");
    	$("#section_tiposervicio").removeClass("hidden");
	});
	$("#NoAgendo").click(function(){
    	$("#section_dir").addClass("hidden");
    	$("#section_date").addClass("hidden");
   		$("#section_tiposervicio").addClass("hidden");
   		$("#DireccionLead").val('');
   		$("#HoraServicioLead").val('--');
   		$("#FechaServicioLead").val('');
   		$("#CiudadLead").val('--');
   		$("#TipoServicioLead").val('--');
    });	
   	$("#CancelarLead").click(function(){
   		$("#DireccionLead").val('');
   		$("#HoraServicioLead").val('--');
   		$("#FechaServicioLead").val('');
   		$("#CiudadLead").val('--');
   		$("#TipoServicioLead").val('--');
   		$("#nombresLead").val('');
   		$("#apellidosLead").val('');
   		$("#emailLead").val('');
   		$("#telefonoLead").val('');
   		$("#celularLead").val('');
   		$("#NoAgendo").val('True')
   	});


</script>
<div class="row">
	<div class="col-md-3"></div>
	<div class="col-md-3">
    <%= f.submit "Guardar" ,class:'btn btn-primary btn-lg' , :style => 'border-radius:5px;'%>
	</div>
	<div class="col-md-3">
	<a href="http://localhost:3000/"><input type="button" value="Volver" class="btn btn-warning btn-lg" id="CancelarLead" style="border-radius: 5px;" /></a>
	</div>
	<div class="col-md-3"></div>
</div>
<% end %>

app/views/leads/_lead.html.erb
<tr>
	<th> <%= lead.id %> </th>
	<td><%= lead.nombres %> <%= lead.apellidos %></td>
	<td><%= lead.agendo_serv %></td>
	<td><%= lead.estado %></td>
	<td><%= lead.tipo_servicio %></td>
	<td><%= lead.ciudad %></td>
	<td><%= lead.fecha_de_servicio %></td>
	<td style="padding: 3px;">
	<%= link_to edit_lead_path(lead), style:'background-color: transparent;' do %>
    <button type="button" class="btn btn-primary btn-circle">
    	<span class="glyphicon glyphicon-pencil"></span>
    </button>
	<% end %>
	</td>

</tr>

app/views/leads/_new.html.erb
<% @lead = Lead.new %>
<%= form_for @lead do |f| %>
<% if @lead.errors.any? %>
<div id="alert alert-danger">
	<h4 class="alert-heading">Oh No!</h4>
	<p>Ha ocurrido un error</p>
<% end %>
<div class="row">
	<div class="form-group col-md-6">
		<%= f.label :nombres, 'Nombres'%>
		<div class="input-group">
           	<span class="input-group-addon">
           		<i class="glyphicon glyphicon-user"></i>
           	</span>			
		<%= f.text_field :nombres, class: 'form-control', placeholder:'Nombres', id:'nombresLead' %>
		<% if @lead.errors[:nombres].any? %>
			<span class="badge badge-pill badge-danger">
				<%= @lead.errors[:nombres].first %>
			</span>
		<% end %>
		</div>
	</div>
	<div class="form-group col-md-6">
		<%= f.label :apellidos, 'Apellidos'%>
		<div class="input-group">
           	<span class="input-group-addon">
           		<i class="glyphicon glyphicon-user"></i>
           	</span>
		<%= f.text_field :apellidos, class: 'form-control', placeholder:'Apellidos', id:'apellidosLead' %>
		<% if @lead.errors[:apellidos].any? %>
			<span class="badge badge-pill badge-danger">
				<%= @lead.errors[:apellidos].first %>
			</span>
		<% end %>
	</div>
	</div>
</div>
<div class="row">
	<div class="form-group col-md-4">
		<%= f.label :email, 'Correo electrónico'%>
		<div class="input-group">
			<span class="input-group-addon">
				<i class="glyphicon glyphicon-envelope"></i>
			</span>
			<%= f.text_field :email, class: 'form-control', placeholder:'Correo electrónico', id:'emailLead' %>
			<% if @lead.errors[:email].any? %>
			<span class="badge badge-pill badge-danger">
				<%= @lead.errors[:email].first %>
			</span>
		<% end %>
		</div>
	</div>
	<div class="form-group col-md-4">
		<%= f.label :telefono, 'Teléfono'%>
		<div class="input-group">
			<span class="input-group-addon">
				<i class="glyphicon glyphicon-phone-alt"></i>
			</span>
		<%= f.text_field :telefono, class: 'form-control', placeholder:'Teléfono' , id:'telefonoLead' %>
		</div>
	</div>
	<div class="form-group col-md-4">
		<%= f.label :celular, 'Celular'%>
		<div class="input-group">
			<span class="input-group-addon">
				<i class="glyphicon glyphicon-earphone"></i>
			</span>
		<%= f.text_field :celular , class: 'form-control', placeholder:'Celular', id:'celularLead' %>
		</div>
	</div>
</div>
<div class="row">
	<div class="col-md-6" style="padding-bottom: 5px;">
		<label for=Pregunta class="form-check-label">
			Le gustaría agendar un servicio?
		</label>
	</div>
	<div class="custom-control custom-radio custom-control-inline" data-toggle="buttons-radio">
		<div class="col-md-3 text-center">
			<%= f.label :agendo_serv, "Si", :value => "true" , class:'custom-control-label'  %>
		    <%= f.radio_button :agendo_serv, "Si" , class:'custom-control-input form-check-input with-gap' , id:'Agendo' %>
		</div>
		<div class="col-md-3">
		    <%= f.label :agendo_serv, "No", :value => "false" , class:'custom-control-label' %>
		    <%= f.radio_button :agendo_serv, "No", :checked => true , class:'custom-control-input form-check-input with-gap', id:'NoAgendo' %>
  		</div>
	</div>
</div>
<div class="row hidden" id="section_tiposervicio">
	<div class="form-group col-md-12">
		<%= f.label :tipo_servicio, "Tipo de Servicio" %>
		 <div class="input-group">
             <span class="input-group-addon" style="max-width: 100%;">
             	<i class="glyphicon glyphicon-list"></i>
             </span>
		<%= f.select :tipo_servicio, ["--","Control Integral de Plagas" , "Recarga de Extintores"],{}, {class: "form-control" , id:'TipoServicioLead'}%>
		</div>
	</div>
</div>
<div class="row hidden" id="section_date">
	<div class="form-group col-md-3">
		<%= f.label :ciudad, "Ciudad" %>
		<div class="input-group">
             <span class="input-group-addon" style="max-width: 100%;">
             	<i class="glyphicon glyphicon-th"></i>
             </span>
		<%= f.select :ciudad, ["--","Cali", "Bogota","Medellin"],{}, {class: "form-control", id:"CiudadLead"}%>
		</div>
	</div>
	<div class="form-group col-md-6">
		<%= f.label :fecha_de_servicio, "Fecha en que necesitas el servicio" %>
            <div class='input-group date' id='datetimepicker1'>
            	<span class="input-group-addon">    
                        <span class="glyphicon glyphicon-calendar"></span>
                </span>
                 <%= f.text_field :fecha_de_servicio, "data-provide" => 'datetimepicker', class: 'form-control' , id:'FechaServicioLead' %>
            </div>
    </div>
    <div class="form-group col-md-3">
		<%= f.label :hora_de_servicio, "Horario" %>
		<div class="input-group">
	    	<span class="input-group-addon">    
		                <span class="glyphicon glyphicon-time"></span>
		    </span>	
		<%= f.select :hora_de_servicio, ['--','Mañana','Medio día','Tarde','Noche'], {}, {class: "form-control", id:'HoraServicioLead'} %>
		</div>
	</div>
</div>
<div class="row hidden" id="section_dir">
	<div class="form-group col-md-12">
		<%= f.label :direccion, "Dirección" %>
		<div class="input-group">
	    	<span class="input-group-addon">    
		         <span class="glyphicon glyphicon-road"></span>
		    </span>
			<%= f.text_field :direccion, class: 'form-control', placeholder:'Dirección', id:'DireccionLead' %>
		</div>
	</div>
</div>
<div class="row">
	<div class="form-group col-md-12">
		<%= f.label :observaciones, "Observaciones (opcional)" %>
		<div class="input-group">
			<span class="input-group-addon">
				<i class="glyphicon glyphicon-text-size"></i>
			</span>
		<%= f.text_area :observaciones, class:'form-control' , id:'ObservacionesLead' %>
		</div>
	</div>
	<div class="hidden">
		<%= f.text_area :estado, :value => "Por contactar"  %>
	</div>
</div>

<script type="text/javascript">
	

    $(function () {
        $('#datetimepicker1').datetimepicker({
        	format: 'DD/MM/YYYY',
        });
    });
    $("#Agendo").click(function(){
    	$("#section_dir").removeClass("hidden");
    	$("#section_date").removeClass("hidden");
    	$("#section_tiposervicio").removeClass("hidden");
	});
	$("#NoAgendo").click(function(){
    	$("#section_dir").addClass("hidden");
    	$("#section_date").addClass("hidden");
   		$("#section_tiposervicio").addClass("hidden");
   		$("#DireccionLead").val('');
   		$("#HoraServicioLead").val('--');
   		$("#FechaServicioLead").val('');
   		$("#CiudadLead").val('--');
   		$("#TipoServicioLead").val('--');
    });	
   	$("#CancelarLead").click(function(){
   		$("#DireccionLead").val('');
   		$("#HoraServicioLead").val('--');
   		$("#FechaServicioLead").val('');
   		$("#CiudadLead").val('--');
   		$("#TipoServicioLead").val('--');
   		$("#nombresLead").val('');
   		$("#apellidosLead").val('');
   		$("#emailLead").val('');
   		$("#telefonoLead").val('');
   		$("#celularLead").val('');
   		$("#NoAgendo").val('True')
   	});


</script>
<div class="row">
	<div class="col-md-3"></div>
	<div class="col-md-3">
    <%= f.submit "Guardar" ,class:'btn btn-primary btn-lg' , :style => 'border-radius:5px;'%>
	</div>
	<div class="col-md-3">
	<a href="http://localhost:3000/"><input type="button" value="Cancelar" class="btn btn-warning btn-lg" id="CancelarLead" style="border-radius: 5px;" /></a>
	</div>
	<div class="col-md-3"></div>
</div>
<% end %>

app/views/leads/index.html.erb
<div class="col-lg-11">
<div class="row">
	<div class="col-lg-12">
		<h3 class="page-header" style="margin-top: 0px;">Leads o Clientes Potenciales</h3>
	</div>
</div>
<div class="row">
	<table id="table_leads"  class="table table-striped table-hover" style="width: 100%">
    <thead>
        <tr>
			<th>#</th>
			<th>Nombre</th>
			<th>Agendó?</th>
			<th>Estado</th>
			<th>Servicio</th>
			<th>Ciudad</th>
			<th>Fecha</th>
			<th></th>
		</tr>
    </thead>
    <tbody>
    	<%= render @leads %>
    </tbody>
	</table>
</div>
</div>

app/views/leads/new.html.erb
<div class="container">
	<h2 class="text-center">Necesitas un servicio o quieres más información?</h2>
    <small class="form-text text-muted text-center">
        <p class="text-center">Diligencia el formulario a continuación y uno de nuestros asesores te contactará en breve</p>
    </small>
<%= render 'leads/form' %>
</div>

app/views/leads/show.html.erb
<table class= "table">
	<thead>
		<tr>
			<th scope="col">#</th>
      		<th scope="col">Nombres</th>
    		<th scope="col">Apellidos</th>
      		<th scope="col">Correo Electrónico</th>
		</tr>
	</thead>
	<tbody>
	    <tr>
	      <th scope="row"> <%= @lead.id %> </th>
	      <td><%= @lead.nombres %></td>
	      <td><%= @lead.apellidos %></td>
	      <td><%= @lead.email %></td>
	    </tr>
	    <tr>
	</tbody>
</table>